"""empty message

Revision ID: a32de0710ec4
Revises: d372a1c0004f
Create Date: 2017-07-26 14:44:24.820214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32de0710ec4'
down_revision = 'd372a1c0004f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_index('ix_comments_timestmp', table_name='comments')
    op.drop_column('comments', 'timestmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestmp', sa.DATETIME(), nullable=True))
    op.create_index('ix_comments_timestmp', 'comments', ['timestmp'], unique=False)
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
